version: "3.8"
services:
  ping:
    image: ghcr.io/evandigby/ping:${VERSION}
    build:
      context: .
      args: 
      - appdir=ping
    environment:
      PING_PONGURL: http://pong:8080/ping
      PING_INTERVAL: 1s
      PING_TIMEOUT: 1s
  pong:
    image: ghcr.io/evandigby/pong:${VERSION}
    build:
      context: .
      args: 
      - appdir=pong
    environment:
      PONG_HOST: :8080
    expose: 
    - "8080"