version: "3.8"
services:
  ping:
    image: docker.pkg.github.com/evandigby/pingpong/ping:${SVC_VERSION}
    build:
      context: .
      args: 
      - appdir=ping
    environment:
      PING_PONGURL: http://pong:8080/ping
      PING_INTERVAL: 1s
      PING_TIMEOUT: 1s
  pong:
    image: docker.pkg.github.com/evandigby/pingpong/pong:${SVC_VERSION}
    build:
      context: .
      args: 
      - appdir=pong
    environment:
      PONG_HOST: :8080
    expose: 
    - "8080"