apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping-deployment
  labels:
    app: ping
spec:
  replicas: 6
  selector:
    matchLabels:
      app: ping
  template:
    metadata:
      labels:
        app: ping
    spec:
      containers:
      - name: ping
        image: ghcr.io/evandigby/ping:latest
        imagePullPolicy: Always
        env:
        - name: PING_PONGURL
          value: http://pong/ping
        - name: PING_INTERVAL
          value: 1s
        - name: PING_TIMEOUT
          value: 1s
        resources:
          requests:
            memory: 32Mi
            cpu: 100m
          limits:
            memory: 64Mi
            cpu: 500m